import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { Observable, map } from 'rxjs';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root',
})
export class AddrequestService {
  constructor(private router: Router, private http: HttpClient) {}

  // category: string[] = [
  //   'Administration business and management',
  //   'Alternative therapies',
  //   'Animals land and environment',
  //   'Computing and ICT',
  //   'Construction and building',
  //   'Design arts and crafts',
  //   'Education and training',
  //   'Engineering',
  //   'Facilities and property services',
  //   'Financial services',
  //   'Garage services',
  //   'Hairdressing and beauty',
  //   'Healthcare',
  //   'Heritage culture and libraries',
  //   'Hospitality catering and tourism',
  //   'Languages',
  //   'Legal and court services',
  //   'Manufacturing and production',
  //   'Performing arts and media',
  //   'Print and publishing marketing and advertising',
  //   'Retail and customer services',
  //   'Science mathematics and statistic',
  //   'Security uniformed and protective services',
  //   'Social sciences and religion',
  //   'Social work and caring services',
  //   'Sport and leisure',
  //   'Transport distribution and logistics',
  // ];
  category: string[] = [
    'Accountant',
    'Administrative',
    'Advisor',
    'Agriculture',
    'Assistant',
    'Cooking',
    'Driver',
    'Engineering',
    'Garments & Textiles',
    'Hotel',
    'House Keeping',
    'Human Resources',
    'IT',
    'ITI',
    'Insurance',
    'Labour',
    'Law',
    'Manager',
    'Manufacturers',
    'Marketing',
    'Media',
    'Medical',
    'Network',
    'Office',
    'Officer',
    'Operators',
    'Others',
    'Security',
    'Supervisor',
    'Teacher',
    'Technician',
    'Trainer',
  ];
  getSubCategory() {
    const subCategory: { [key: string]: string[] } = {
      Accountant: [
        'Account Assistant',
        'Accountant',
        'Accounts Manager',
        'Audit Assistant',
        'Cashier',
        'Auditor',
        'Chartered Accountant',
        'Financial Advisor',
      ],
      Administrative: [
        'Academic Coordinator',
        'Accessories Incharge',
        'Accounts Manager',
        'Administration Manager',
        'Administrator',
        'Assistant Manager',
        'Auditor',
        'BPO Executive',
        'Branch Manager',
        'Branch Officer',
        'Branch Supervisor',
        'Building Supervisor',
        'Business Development Executive',
        'Canteen Incharge',
        'Canteen Supervisor',
        'Chartered Accountant',
        'Checking Supervisor',
        'Civil Supervisor',
        'Construction Supervisor',
        'Customer Care',
        'Customer Care Executive',
        'Customer Relationship Manager',
        'Customer Support Officer',
        'Digital Marketing Executive',
        'Electrical Supervisor',
        'Event Organizer',
        'Executive',
        'Fabric Incharge',
        'Farm Executive',
        'Farm Incharge',
        'Farm Manager',
        'Field Executive',
        'General Manager',
        'Godown Incharge',
        'Hospital Administrator',
        'Hotel Manager',
        'HR Admin',
        'Incharge',
        'Librarian',
        'Management Staff',
        'Manager',
        'Marketing Associate',
        'Marketing Executive',
        'Marketing Head',
        'Marketing Incharge',
        'Marketing Manager',
        'Marketing Supervisor',
        'Mechanical Supervisor',
        'Office Administrator',
        'Office Executive',
        'Office Incharge',
        'Office Maintenance',
        'Office Manager',
        'Office Supervisor',
        'Operation Executive',
        'Principal',
        'Production Staff',
        'Representative',
        'Sales Administrator',
        'Sales Associate',
        'Sales Coordinator',
        'Sales Executive',
        'Sales Incharge',
        'Sales Manager',
        'Sales Representative',
        'Sales Supervisor',
        'Security Head',
        'Security Incharge',
        'Security Manager',
        'Security Supervisor',
        'Site Supervisor',
        'Store Manager',
        'Supervisor',
        'System Administrator',
        'Team Leader',
        'Tele Marketing',
        'Transport Coordinator',
        'Vice Principal',
        'Warehouse Manager',
      ],
      Advisor: [
        'Advisor',
        'Consultant',
        'Diet Consultant',
        'Financial Advisor',
        'Insurance Advisor',
        'Legal Advisor',
        'Legal Consultant',
        'Marketing Advisor',
        'Sales Advisor',
        'Sales Consultant',
      ],
      Agriculture: [
        'Agricultural Engineering Professor',
        'Agricultural Field Staff',
        'Agriculture Professor',
        'Cattle Maintenance',
        'Farm Executive',
        'Farm Incharge',
        'Farm Manager',
        'Farm Supervisor',
        'Farm Worker',
        'Farmer',
        'Gardener',
        'Seedling Planting Machine Driver',
      ],
      Assistant: [
        'Account Assistant',
        'Assistant',
        'Assistant Cook',
        'Audit Assistant',
        'Beautician Helper',
        'Centering Helper',
        'Helper',
        'Lab Assistant',
        'Librarian Assistant',
        'Marketing Assistant',
        'Nurse Assistant',
        'Office Assistant',
        'Office Boy',
        'Peon',
        'Personal Assistant',
        'Pharmacy Assistant',
        'Sales Assistant',
        'Security Assistant',
      ],
      Cook: [
        'Assistant Cook',
        'Barbeque Chef',
        'Biryani Master',
        'Bread Master',
        'Cake Master',
        'Catering Master',
        'Chaat Master',
        'Chettinadu Master',
        'Chinese Chef',
        'Continental Chef',
        'Cooking',
        'Cooking Master',
        'Dosa Master',
        'Home Cooking',
        'Juice Master',
        'Karam Master',
        'Kitchen Master',
        'Palaharam Master',
        'Parotta Master',
        'Shawarma Master',
        'Soup Master',
        'Sweet Master',
        'Tea Master',
        'Thanthuri Master',
      ],
      Driver: [
        'Ambulance Driver',
        'Auto Driver',
        'Bike Driver',
        'Bus Driver',
        'Car Driver',
        'Driver',
        'JCB Driver',
        'Lorry Driver',
        'Seedling Planting Machine Driver',
        'Tata Ace Driver',
        'Tractor Driver',
      ],
      Engineer: [
        'Architect',
        'Assembly Engineer',
        'Auto Cad Designer',
        'Autocad Draftsman',
        'Autocad Engineer',
        'CADD Engineer',
        'Civil Engineer',
        'CNC Programmer',
        'Computer Engineer',
        'Computer Service Engineer',
        'Drafts Man',
        'Electrical Engineer',
        'Embedded Developer',
        'Embedded Engineer',
        'Field Service Engineer',
        'Hardware Engineer',
        'Mechanical Engineer',
        'Network Engineer',
        'Plant Engineer',
        'Quality Controller',
        'Software Engineer',
        'Testing Engineer',
      ],
      'Garments & Textiles': [
        'Embroidery Designer',
        'Fabric Incharge',
        'Fashion Designer',
        'Flat Lock Tailor',
        'Overlock Tailor',
        'Packing Staff',
        'Quality Controller',
        'Singer Tailor',
        'Tailor',
      ],
      Hotel: [
        'Bar Waiter',
        'Barbeque Chef',
        'Canteen Incharge',
        'Canteen Supervisor',
        'Captain',
        'Catering Master',
        'Chettinadu Master',
        'Chinese Chef',
        'Continental Chef',
        'Hotel Manager',
        'Mess Staff',
        'Parcel Staff',
        'Restaurant Worker',
        'Room Service',
        'Shawarma Master',
        'Supplier',
        'Sweet Master',
        'Waiter',
      ],
      'House Keeping': ['Cleaning Worker', 'House Keeping', 'Sweeper'],
      'Human Resources': ['HR Admin', 'Placement Officer'],
      IT: [
        '.Net Developer',
        '.Net Trainer',
        'Album Designer',
        'Android Developer',
        'Android Trainer',
        'Asp.Net Developer',
        'C++ Developer',
        'Data Analyst',
        'Database Developer',
        'Graphic Designer',
        'IOS Developer',
        'Java Developer',
        'Photoshop Designer',
        'PHP Trainer',
        'PHP/Web Developer',
        'Programmer',
        'SEO Analyst',
        'Software Engineer',
        'Software Tester',
        'SQL Developer',
        'System Administrator',
        'Testing Engineer',
        'UI/UX Designer',
        'Video Editor',
        'Videographer',
        'WordPress Developer',
      ],
      ITI: [
        'A/C Technician',
        'Aluminium Welder',
        'Aluminum Fabricator',
        'ARC Welder',
        'Bending Machine Operator',
        'Bike Mechanic',
        'Borewell Driller',
        'Car Mechanic',
        'Carpenter',
        'CCTV Technician',
        'Centering Fitter',
        'CNC and HMC Operator',
        'CNC and VMC Operator',
        'CNC and VTL Operator',
        'CNC and VTL Setter',
        'CNC Laser Machine Operator',
        'CNC Lathe Operator',
        'CNC Machine Operator',
        'CNC Setter',
        'CNC Turner',
        'CNC Turning Lathe Operator',
        'CNC Turning Machine Operator',
        'CNC Turning Setter',
        'Computer Service Engineer',
        'Cutting Machine Operator',
        'Dyeing Fitter',
        'Electrical Maintenance',
        'Electrician',
        'Electrician cum Plumber',
        'Fabricator',
        'Field Service Engineer',
        'Fitter',
        'Flex Board Fitter',
        'Gas Welder',
        'HMC Operator',
        'HMC Setter',
        'Hydraulic Fitter',
        'Injection Moulding Machine Operator',
        'Lathe Operator',
        'Lathe Turner',
        'Lathe Welder',
        'Machine Operator',
        'Mechanic',
        'Mig Welder',
        'Motor Mechanic',
        'Plumber',
        'Rubber Moulding Machine Operator',
        'Service Technician',
        'Setter',
        'Solar Technician',
        'Spinning Operator',
        'Tig Welder',
        'Tractor Mechanic',
        'Turner',
        'VMC Operator',
        'VMC Programmer',
        'VMC Setter',
        'VML Operator',
        'VTL Operator',
        'VTL Programmer',
        'VTL Setter',
        'Welder',
        'Wheel Alignment Technician',
        'Winder',
        'Workshop Mechanic',
        'WTP Operator',
      ],
      Insurance: ['Insurance Advisor'],
      Labour: [
        'Assembly Worker',
        'Carpenter',
        'Cleaner',
        'Delivery Boy',
        'Delivery Staff',
        'Laundry Worker',
        'Loadman',
        'Painter',
        'Plumber',
        'Water Wash Boy',
        'Wireman',
        'Worker',
      ],
      Law: ['Legal Consultant', 'Legal Advisor', 'Junior Advocate'],
      Manager: [
        'Accounts Manager',
        'Administration Manager',
        'Assistant Manager',
        'Branch Manager',
        'Customer Relationship Manager',
        'Farm Manager',
        'General Manager',
        'Hotel Manager',
        'Manager',
        'Marketing Manager',
        'Office Manager',
        'Sales Manager',
        'Security Manager',
        'Store Manager',
        'Warehouse Manager',
      ],
      Manufacturers: [],
      Marketing: [
        'Business Development Executive',
        'Collection Staff',
        'Delivery Boy',
        'Delivery Staff',
        'Digital Marketing Executive',
        'Field Executive',
        'Field Worker',
        'Marketing Advisor',
        'Marketing Assistant',
        'Marketing Associate',
        'Marketing Executive',
        'Marketing Head',
        'Marketing Incharge',
        'Marketing Manager',
        'Marketing Officer',
        'Marketing Staff',
        'Marketing Supervisor',
        'Medical Sales Representative',
        'Sales Administrator',
        'Sales Advisor',
        'Sales Assistant',
        'Sales Associate',
        'Sales Consultant',
        'Sales Coordinator',
        'Sales Executive',
        'Sales Incharge',
        'Sales Manager',
        'Sales Officer',
        'Sales Representative',
        'Sales Staff',
        'Sales Supervisor',
        'Tele Marketing',
      ],
      Media: [
        'Album Designer',
        'Camera Man',
        'Corel Draw Designer',
        'Designer',
        'Flex Designer',
        'Graphic Designer',
        'Journalist',
        'Photographer',
        'Photoshop Designer',
        'Reporter',
        'UI/UX Designer',
        'Video Editor',
        'Videographer',
      ],
      Medical: [
        'Ayurveda Therapist',
        'Baby Care',
        'Dentist',
        'Doctor',
        'General Duty Medical Officer',
        'Home Nurse',
        'Hospital Administrator',
        'Medical Sales Representative',
        'Nurse',
        'Nurse Assistant',
        'Patient Care Taker',
        'Pharmacist',
        'Pharmacy Assistant',
        'Siddha Doctor',
        'Therapist',
        'Veterinary Doctor',
        'X-Ray Technician',
      ],
      Network: ['Network Engineer', 'Cable Operator'],
      Office: [
        'Accessories Incharge',
        'Account Assistant',
        'Accountant',
        'Administrator',
        'Admission Officer',
        'Audit Assistant',
        'Billing',
        'BPO - Non Voice',
        'BPO - Voice',
        'BPO Executive',
        'Branch Manager',
        'Branch Officer',
        'Cashier',
        'Chartered Accountant',
        'Clerk',
        'Computer Operator',
        'Content Developer',
        'Customer Care',
        'Customer Care Executive',
        'Customer Relationship Manager',
        'Customer Support Officer',
        'Data Entry Operator',
        'Digital Marketing Executive',
        'Front Office Coordinator',
        'General Manager',
        'Librarian',
        'Librarian Assistant',
        'Manager',
        'Office Administrator',
        'Office Assistant',
        'Office Boy',
        'Office Executive',
        'Office Incharge',
        'Office Maintenance',
        'Office Manager',
        'Office Staff',
        'Office Supervisor',
        'Peon',
        'Project Staff',
        'Receptionist',
        'Steno Typist',
        'Store Keeper',
        'Store Manager',
        'Supervisor',
        'System Administrator',
        'Team Leader',
        'Tele Marketing',
        'Telecaller',
        'Typist',
      ],
      Officer: [
        'Admission Officer',
        'Branch Officer',
        'Customer Support Officer',
        'General Duty Medical Officer',
        'Marketing Officer',
        'Placement Officer',
        'Sales Officer',
        'Security Officer',
      ],
      Operators: [
        'Bending Machine Operator',
        'Buffing Machine Operator',
        'Cable Operator',
        'CNC and HMC Operator',
        'CNC and VMC Operator',
        'CNC and VTL Operator',
        'CNC and VTL Setter',
        'CNC Laser Machine Operator',
        'CNC Lathe Operator',
        'CNC Machine Operator',
        'CNC Setter',
        'CNC Turner',
        'CNC Turning Lathe Operator',
        'CNC Turning Machine Operator',
        'CNC Turning Setter',
        'Crane Operator',
        'Cutting Machine Operator',
        'DRO Machine Operator',
        'HMC Operator',
        'Injection Moulding Machine Operator',
        'Lathe Operator',
        'Lathe Turner',
        'Machine Operator',
        'Petrol Pump Operator',
        'Rubber Moulding Machine Operator',
        'Spinning Operator',
        'VMC Operator',
        'VML Operator',
        'VTL Operator',
        'WTP Operator',
        'Xerox Operator',
      ],
      Others: [
        'Barber',
        'Beautician',
        'Blacksmith',
        'Checker',
        'Distributors',
        'Draughtsman',
        'Godown Incharge',
        'Gold Appraiser',
        'Hair Stylist',
        'House Maid',
        'Interior Designer',
        'Ironing',
        'Maintenance',
        'Massage Therapist',
        'Petrol Pump Operator',
        'Purchase Staff',
        'Spa Therapist',
        'Tour Guide',
        'Weaver',
        'Yarn Matching',
        'Yoga Master',
      ],
      Security: [
        'Hostel Warden',
        'Security',
        'Security Assistant',
        'Security Guard',
        'Security Head',
        'Security Incharge',
        'Security Manager',
        'Security Officer',
        'Security Supervisor',
        'Warden',
        'Watchman',
      ],
      Supervisor: [
        'Branch Supervisor',
        'Building Supervisor',
        'Canteen Supervisor',
        'Checking Supervisor',
        'Civil Supervisor',
        'Construction Supervisor',
        'Electrical Supervisor',
        'Farm Supervisor',
        'Marketing Supervisor',
        'Mechanical Supervisor',
        'Office Supervisor',
        'Sales Supervisor',
        'Security Supervisor',
        'Site Supervisor',
        'Supervisor',
      ],
      Teacher: [
        'Abacus Teacher',
        'Accountancy Professor',
        'Accountancy Teacher',
        'Agricultural Engineering Professor',
        'Agriculture Professor',
        'Architecture Professor',
        'Art Teacher',
        'Assistant Professor',
        'Associate Professor',
        'Automobile Engineering Professor',
        'Bio Informatics Professor',
        'Bio Medical Engineering Professor',
        'Biochemistry Lecturer',
        'Biochemistry Professor',
        'Biology Professor',
        'Biology Teacher',
        'Biotechnology Professor',
        'Biotechnology Teacher',
        'Botany Lecturer',
        'Botany Professor',
        'Botany Teacher',
        'Business Economics Lecturer',
        'Business Maths Teacher',
        'Catering Lecturer',
        'Chemical Engineering Lecturer',
        'Chemical Engineering Professor',
        'Chemistry Lecturer',
        'Chemistry Professor',
        'Chemistry Teacher',
        'Civil Engineering Lecturer',
        'Civil Engineering Professor',
        'Commerce Lecturer',
        'Commerce Professor',
        'Commerce Teacher',
        'Computer Application Lecturer',
        'Computer Lecturer',
        'Computer Science Lecturer',
        'Computer Science Professor',
        'Computer Science Teacher',
        'Dance Teacher',
        'Economics Lecturer',
        'Economics Professor',
        'Economics Teacher',
        'English Lecturer',
        'English Professor',
        'English Teacher',
        'Geography Professor',
        'Geography Teacher',
        'Hindi Teacher',
        'History Lecturer',
        'History Professor',
        'History Teacher',
        'Information Technology Lecturer',
        'Information Technology Professor',
        'Karate Teacher',
        'KG Teacher',
        'Lecturer',
        'Maths Lecturer',
        'Maths Professor',
        'Maths Teacher',
        'Mechanical Lecturer',
        'Mechanical Professor',
        'Microbiology Lecturer',
        'Microbiology Professor',
        'Microbiology Teacher',
        'Montessori Teacher',
        'Music Teacher',
        'Physical Education Teacher',
        'Physics Lecturer',
        'Physics Professor',
        'Physics Teacher',
        'Physiology Lecturer',
        'Primary Teacher',
        'Principal',
        'Professor',
        'Psychology Lecturer',
        'Psychology Professor',
        'Psychology Teacher',
        'Science Teacher',
        'Silambam Teacher',
        'Social Science Teacher',
        'Sociology Lecturer',
        'Sociology Professor',
        'Sociology Teacher',
        'Spoken English Teacher',
        'Tamil Lecturer',
        'Tamil Professor',
        'Tamil Teacher',
        'Tuition Master',
        'Vice Principal',
        'Zoology Lecturer',
        'Zoology Professor',
        'Zoology Teacher',
      ],
      Technician: [
        'A/C Technician',
        'CCTV Technician',
        'Field Service Engineer',
        'Lab Technician',
        'RO Technician',
        'Service Technician',
        'Solar Technician',
        'Technician',
        'Wheel Alignment Technician',
        'X-Ray Technician',
      ],
      Trainer:[".Net Trainer",
      "Android Trainer",
      "Beautician Trainer",
      "CADD Trainer",
      "PHP Trainer",
      "Physical Education Trainer",
      "Spoken English Trainer",
      ]
    };
    // console.log(val)
    return subCategory;
  }

  request(data: FormData) {
    return this.http.post(`${environment.apiUrl}api/v1/addRequest`, data);
  }

  get() {
    return this.http.get(`${environment.apiUrl}api/v1/demo`);
  }
}
